### ISSUE TITLE
Fails to build with GHC 9.2

### ISSUE THREAD

**Issue by Bodigrim** [Shimuuar/type-level-numbers#1]
```
type-level-numbers-0.1.1.1$ cabal build -w ghc-9.2
Resolving dependencies...
Build profile: -w ghc-9.2.3 -O1
In order, the following will be built (use -v for more details):
 - type-level-numbers-0.1.1.1 (lib) (first run)
Configuring library for type-level-numbers-0.1.1.1..
Preprocessing library for type-level-numbers-0.1.1.1..
Building library for type-level-numbers-0.1.1.1..
[ 1 of 10] Compiling TypeLevel.Number.Classes ( TypeLevel/Number/Classes.hs, /private/tmp/type-level-numbers-0.1.1.1/dist-newstyle/build/x86_64-osx/ghc-9.2.3/type-level-numbers-0.1.1.1/build/TypeLevel/Number/Classes.o, /private/tmp/type-level-numbers-0.1.1.1/dist-newstyle/build/x86_64-osx/ghc-9.2.3/type-level-numbers-0.1.1.1/build/TypeLevel/Number/Classes.dyn_o )

TypeLevel/Number/Classes.hs:109:10: error:
    • Non type-variable argument
        in the constraint: OneOfTwo (Compare n m) IsLesser IsEqual
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘LesserEq n m’
    |
109 | instance (OneOfTwo (Compare n m) IsLesser  IsEqual) => LesserEq n m
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeLevel/Number/Classes.hs:110:10: error:
    • Non type-variable argument
        in the constraint: OneOfTwo (Compare n m) IsGreater IsEqual
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘GreaterEq n m’
    |
110 | instance (OneOfTwo (Compare n m) IsGreater IsEqual) => GreaterEq n m
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It would be great to make revisions for existing releases.

**Comment by Shimuuar** [comment]
I've uploaded 0.1.1.2 and added constraints on already uploaded packages. 

Last update was for 7.8. That's quite a run!
